FROM mcr.microsoft.com/powershell:latest
LABEL description="Based on the Microfot Ubuntu 18.04 for Linux PowerShell Dockerfile that will download and start Universal Dashboard Community on port 8080" 

# FROM: https://hub.docker.com/_/microsoft-powershell
# Build: docker build . --tag=universaldashboarddemo
# Run: docker run -it -p 8080:8080 universaldashboarddemo:latest 

EXPOSE 8080
COPY [ "./startdashboard.ps1", "/home/startdashboard.ps1" ]
ENTRYPOINT ["pwsh", "/home/startdashboard.ps1"]