using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace UniversalDashboard.Models
{
    public enum FontAwesomeIcons
	{
		None,
		ad,
		address_book,
		address_card,
		adjust,
		air_freshener,
		align_center,
		align_justify,
		align_left,
		align_right,
		allergies,
		ambulance,
		american_sign_language_interpreting,
		anchor,
		angle_double_down,
		angle_double_left,
		angle_double_right,
		angle_double_up,
		angle_down,
		angle_left,
		angle_right,
		angle_up,
		angry,
		ankh,
		apple_alt,
		archive,
		archway,
		arrow_alt_circle_down,
		arrow_alt_circle_left,
		arrow_alt_circle_right,
		arrow_alt_circle_up,
		arrow_circle_down,
		arrow_circle_left,
		arrow_circle_right,
		arrow_circle_up,
		arrow_down,
		arrow_left,
		arrow_right,
		arrows_alt,
		arrows_alt_h,
		arrows_alt_v,
		arrow_up,
		assistive_listening_systems,
		asterisk,
		at,
		atlas,
		atom,
		audio_description,
		award,
		baby,
		baby_carriage,
		backspace,
		backward,
		balance_scale,
		ban,
		band_aid,
		barcode,
		bars,
		baseball_ball,
		basketball_ball,
		bath,
		battery_empty,
		battery_full,
		battery_half,
		battery_quarter,
		battery_three_quarters,
		bed,
		beer,
		bell,
		bell_slash,
		bezier_curve,
		bible,
		bicycle,
		binoculars,
		biohazard,
		birthday_cake,
		blender,
		blender_phone,
		blind,
		blog,
		bold,
		bolt,
		bomb,
		bone,
		bong,
		book,
		book_dead,
		bookmark,
		book_open,
		book_reader,
		bowling_ball,
		box,
		boxes,
		box_open,
		braille,
		brain,
		briefcase,
		briefcase_medical,
		broadcast_tower,
		broom,
		brush,
		bug,
		building,
		bullhorn,
		bullseye,
		burn,
		bus,
		bus_alt,
		business_time,
		calculator,
		calendar,
		calendar_alt,
		calendar_check,
		calendar_day,
		calendar_minus,
		calendar_plus,
		calendar_times,
		calendar_week,
		camera,
		camera_retro,
		campground,
		candy_cane,
		cannabis,
		capsules,
		car,
		car_alt,
		car_battery,
		car_crash,
		caret_down,
		caret_left,
		caret_right,
		caret_square_down,
		caret_square_left,
		caret_square_right,
		caret_square_up,
		caret_up,
		carrot,
		car_side,
		cart_arrow_down,
		cart_plus,
		cash_register,
		cat,
		certificate,
		chair,
		chalkboard,
		chalkboard_teacher,
		charging_station,
		chart_area,
		chart_bar,
		chart_line,
		chart_pie,
		check,
		check_circle,
		check_double,
		check_square,
		chess,
		chess_bishop,
		chess_board,
		chess_king,
		chess_knight,
		chess_pawn,
		chess_queen,
		chess_rook,
		chevron_circle_down,
		chevron_circle_left,
		chevron_circle_right,
		chevron_circle_up,
		chevron_down,
		chevron_left,
		chevron_right,
		chevron_up,
		child,
		church,
		circle,
		circle_notch,
		city,
		clipboard,
		clipboard_check,
		clipboard_list,
		clock,
		clone,
		closed_captioning,
		cloud,
		cloud_download_alt,
		cloud_meatball,
		cloud_moon,
		cloud_moon_rain,
		cloud_rain,
		cloud_showers_heavy,
		cloud_sun,
		cloud_sun_rain,
		cloud_upload_alt,
		cocktail,
		code,
		code_branch,
		coffee,
		cog,
		cogs,
		coins,
		columns,
		comment,
		comment_alt,
		comment_dollar,
		comment_dots,
		comments,
		comments_dollar,
		comment_slash,
		compact_disc,
		compass,
		compress,
		compress_arrows_alt,
		concierge_bell,
		cookie,
		cookie_bite,
		copy,
		copyright,
		couch,
		credit_card,
		crop,
		crop_alt,
		cross,
		crosshairs,
		crow,
		crown,
		cube,
		cubes,
		cut,
		database,
		deaf,
		democrat,
		desktop,
		dharmachakra,
		diagnoses,
		dice,
		dice_d20,
		dice_d6,
		dice_five,
		dice_four,
		dice_one,
		dice_six,
		dice_three,
		dice_two,
		digital_tachograph,
		directions,
		divide,
		dizzy,
		dna,
		dog,
		dollar_sign,
		dolly,
		dolly_flatbed,
		donate,
		door_closed,
		door_open,
		dot_circle,
		dove,
		download,
		drafting_compass,
		dragon,
		draw_polygon,
		drum,
		drum_steelpan,
		drumstick_bite,
		dumbbell,
		dumpster,
		dumpster_fire,
		dungeon,
		edit,
		eject,
		ellipsis_h,
		ellipsis_v,
		envelope,
		envelope_open,
		envelope_open_text,
		envelope_square,
		equals,
		eraser,
		ethernet,
		euro_sign,
		exchange_alt,
		exclamation,
		exclamation_circle,
		exclamation_triangle,
		expand,
		expand_arrows_alt,
		external_link_alt,
		external_link_square_alt,
		eye,
		eye_dropper,
		eye_slash,
		fast_backward,
		fast_forward,
		fax,
		feather,
		feather_alt,
		female,
		fighter_jet,
		file,
		file_alt,
		file_archive,
		file_audio,
		file_code,
		file_contract,
		file_csv,
		file_download,
		file_excel,
		file_export,
		file_image,
		file_import,
		file_invoice,
		file_invoice_dollar,
		file_medical,
		file_medical_alt,
		file_pdf,
		file_powerpoint,
		file_prescription,
		file_signature,
		file_upload,
		file_video,
		file_word,
		fill,
		fill_drip,
		film,
		filter,
		fingerprint,
		fire,
		fire_alt,
		fire_extinguisher,
		first_aid,
		fish,
		fist_raised,
		flag,
		flag_checkered,
		flag_usa,
		flask,
		flushed,
		folder,
		folder_minus,
		folder_open,
		folder_plus,
		font,
		font_awesome_logo_full,
		football_ball,
		forward,
		frog,
		frown,
		frown_open,
		funnel_dollar,
		futbol,
		gamepad,
		gas_pump,
		gavel,
		gem,
		genderless,
		ghost,
		gift,
		gifts,
		glass_cheers,
		glasses,
		glass_martini,
		glass_martini_alt,
		glass_whiskey,
		globe,
		globe_africa,
		globe_americas,
		globe_asia,
		globe_europe,
		golf_ball,
		gopuram,
		graduation_cap,
		greater_than,
		greater_than_equal,
		grimace,
		grin,
		grin_alt,
		grin_beam,
		grin_beam_sweat,
		grin_hearts,
		grin_squint,
		grin_squint_tears,
		grin_stars,
		grin_tears,
		grin_tongue,
		grin_tongue_squint,
		grin_tongue_wink,
		grin_wink,
		grip_horizontal,
		grip_lines,
		grip_lines_vertical,
		grip_vertical,
		guitar,
		hammer,
		hamsa,
		hand_holding,
		hand_holding_heart,
		hand_holding_usd,
		hand_lizard,
		hand_paper,
		hand_peace,
		hand_point_down,
		hand_pointer,
		hand_point_left,
		hand_point_right,
		hand_point_up,
		hand_rock,
		hands,
		hand_scissors,
		handshake,
		hands_helping,
		hand_spock,
		hanukiah,
		hashtag,
		hat_wizard,
		haykal,
		hdd,
		heading,
		headphones,
		headphones_alt,
		headset,
		heart,
		heartbeat,
		heart_broken,
		helicopter,
		highlighter,
		hiking,
		hippo,
		history,
		hockey_puck,
		holly_berry,
		home,
		horse,
		horse_head,
		hospital,
		hospital_alt,
		hospital_symbol,
		hotel,
		hot_tub,
		hourglass,
		hourglass_end,
		hourglass_half,
		hourglass_start,
		house_damage,
		hryvnia,
		h_square,
		icicles,
		i_cursor,
		id_badge,
		id_card,
		id_card_alt,
		igloo,
		image,
		images,
		inbox,
		indent,
		industry,
		infinity,
		info,
		info_circle,
		italic,
		jedi,
		joint,
		journal_whills,
		kaaba,
		key,
		keyboard,
		khanda,
		kiss,
		kiss_beam,
		kiss_wink_heart,
		kiwi_bird,
		landmark,
		language,
		laptop,
		laptop_code,
		laugh,
		laugh_beam,
		laugh_squint,
		laugh_wink,
		layer_group,
		leaf,
		lemon,
		less_than,
		less_than_equal,
		level_down_alt,
		level_up_alt,
		life_ring,
		lightbulb,
		link,
		lira_sign,
		list,
		list_alt,
		list_ol,
		list_ul,
		location_arrow,
		_lock,
		lock_open,
		long_arrow_alt_down,
		long_arrow_alt_left,
		long_arrow_alt_right,
		long_arrow_alt_up,
		low_vision,
		luggage_cart,
		magic,
		magnet,
		mail_bulk,
		male,
		map,
		map_marked,
		map_marked_alt,
		map_marker,
		map_marker_alt,
		map_pin,
		map_signs,
		marker,
		mars,
		mars_double,
		mars_stroke,
		mars_stroke_h,
		mars_stroke_v,
		mask,
		medal,
		medkit,
		meh,
		meh_blank,
		meh_rolling_eyes,
		memory,
		menorah,
		mercury,
		meteor,
		microchip,
		microphone,
		microphone_alt,
		microphone_alt_slash,
		microphone_slash,
		microscope,
		minus,
		minus_circle,
		minus_square,
		mitten,
		mobile,
		mobile_alt,
		money_bill,
		money_bill_alt,
		money_bill_wave,
		money_bill_wave_alt,
		money_check,
		money_check_alt,
		monument,
		moon,
		mortar_pestle,
		mosque,
		motorcycle,
		mountain,
		mouse_pointer,
		mug_hot,
		music,
		network_wired,
		neuter,
		newspaper,
		not_equal,
		notes_medical,
		object_group,
		object_ungroup,
		oil_can,
		om,
		otter,
		outdent,
		paint_brush,
		paint_roller,
		palette,
		pallet,
		paperclip,
		paper_plane,
		parachute_box,
		paragraph,
		parking,
		passport,
		pastafarianism,
		paste,
		pause,
		pause_circle,
		paw,
		peace,
		pen,
		pen_alt,
		pencil_alt,
		pencil_ruler,
		pen_fancy,
		pen_nib,
		pen_square,
		people_carry,
		percent,
		percentage,
		person_booth,
		phone,
		phone_slash,
		phone_square,
		phone_volume,
		piggy_bank,
		pills,
		place_of_worship,
		plane,
		plane_arrival,
		plane_departure,
		play,
		play_circle,
		plug,
		plus,
		plus_circle,
		plus_square,
		podcast,
		poll,
		poll_h,
		poo,
		poop,
		poo_storm,
		portrait,
		pound_sign,
		power_off,
		pray,
		praying_hands,
		prescription,
		prescription_bottle,
		prescription_bottle_alt,
		print,
		procedures,
		project_diagram,
		puzzle_piece,
		qrcode,
		question,
		question_circle,
		quidditch,
		quote_left,
		quote_right,
		quran,
		radiation,
		radiation_alt,
		rainbow,
		random,
		receipt,
		recycle,
		redo,
		redo_alt,
		registered,
		reply,
		reply_all,
		republican,
		restroom,
		retweet,
		ribbon,
		ring,
		road,
		robot,
		rocket,
		route,
		rss,
		rss_square,
		ruble_sign,
		ruler,
		ruler_combined,
		ruler_horizontal,
		ruler_vertical,
		running,
		rupee_sign,
		sad_cry,
		sad_tear,
		satellite,
		satellite_dish,
		save,
		school,
		screwdriver,
		scroll,
		sd_card,
		search,
		search_dollar,
		search_location,
		search_minus,
		search_plus,
		seedling,
		server,
		shapes,
		share,
		share_alt,
		share_alt_square,
		share_square,
		shekel_sign,
		shield_alt,
		ship,
		shipping_fast,
		shoe_prints,
		shopping_bag,
		shopping_basket,
		shopping_cart,
		shower,
		shuttle_van,
		sign,
		signal,
		signature,
		sign_in_alt,
		sign_language,
		sign_out_alt,
		sim_card,
		sitemap,
		skating,
		skiing,
		skiing_nordic,
		skull,
		skull_crossbones,
		slash,
		sleigh,
		sliders_h,
		smile,
		smile_beam,
		smile_wink,
		smog,
		smoking,
		smoking_ban,
		sms,
		snowboarding,
		snowflake,
		snowman,
		snowplow,
		socks,
		solar_panel,
		sort,
		sort_alpha_down,
		sort_alpha_up,
		sort_amount_down,
		sort_amount_up,
		sort_down,
		sort_numeric_down,
		sort_numeric_up,
		sort_up,
		spa,
		space_shuttle,
		spider,
		spinner,
		splotch,
		spray_can,
		square,
		square_full,
		square_root_alt,
		stamp,
		star,
		star_and_crescent,
		star_half,
		star_half_alt,
		star_of_david,
		star_of_life,
		step_backward,
		step_forward,
		stethoscope,
		sticky_note,
		stop,
		stop_circle,
		stopwatch,
		store,
		store_alt,
		stream,
		street_view,
		strikethrough,
		stroopwafel,
		subscript,
		subway,
		suitcase,
		suitcase_rolling,
		sun,
		superscript,
		surprise,
		swatchbook,
		swimmer,
		swimming_pool,
		synagogue,
		sync,
		sync_alt,
		syringe,
		table,
		tablet,
		tablet_alt,
		table_tennis,
		tablets,
		tachometer_alt,
		tag,
		tags,
		tape,
		tasks,
		taxi,
		teeth,
		teeth_open,
		temperature_high,
		temperature_low,
		tenge,
		terminal,
		text_height,
		text_width,
		th,
		theater_masks,
		thermometer,
		thermometer_empty,
		thermometer_full,
		thermometer_half,
		thermometer_quarter,
		thermometer_three_quarters,
		th_large,
		th_list,
		thumbs_down,
		thumbs_up,
		thumbtack,
		ticket_alt,
		times,
		times_circle,
		tint,
		tint_slash,
		tired,
		toggle_off,
		toggle_on,
		toilet,
		toilet_paper,
		toolbox,
		tools,
		tooth,
		torah,
		torii_gate,
		tractor,
		trademark,
		traffic_light,
		train,
		tram,
		transgender,
		transgender_alt,
		trash,
		trash_alt,
		tree,
		trophy,
		truck,
		truck_loading,
		truck_monster,
		truck_moving,
		truck_pickup,
		tshirt,
		tty,
		tv,
		umbrella,
		umbrella_beach,
		underline,
		undo,
		undo_alt,
		universal_access,
		university,
		unlink,
		unlock,
		unlock_alt,
		upload,
		user,
		user_alt,
		user_alt_slash,
		user_astronaut,
		user_check,
		user_circle,
		user_clock,
		user_cog,
		user_edit,
		user_friends,
		user_graduate,
		user_injured,
		user_lock,
		user_md,
		user_minus,
		user_ninja,
		user_plus,
		users,
		users_cog,
		user_secret,
		user_shield,
		user_slash,
		user_tag,
		user_tie,
		user_times,
		utensils,
		utensil_spoon,
		vector_square,
		venus,
		venus_double,
		venus_mars,
		vial,
		vials,
		video,
		video_slash,
		vihara,
		volleyball_ball,
		volume_down,
		volume_mute,
		volume_off,
		volume_up,
		vote_yea,
		vr_cardboard,
		walking,
		wallet,
		warehouse,
		water,
		weight,
		weight_hanging,
		wheelchair,
		wifi,
		wind,
		window_close,
		window_maximize,
		window_minimize,
		window_restore,
		wine_bottle,
		wine_glass,
		wine_glass_alt,
		won_sign,
		wrench,
		x_ray,
		yen_sign,
		yin_yang,
		_500px,
		accessible_icon,
		accusoft,
		acquisitions_incorporated,
		adn,
		adobe,
		adversal,
		affiliatetheme,
		algolia,
		alipay,
		amazon,
		amazon_pay,
		amilia,
		android,
		angellist,
		angrycreative,
		angular,
		apper,
		apple,
		apple_pay,
		app_store,
		app_store_ios,
		artstation,
		asymmetrik,
		atlassian,
		audible,
		autoprefixer,
		avianex,
		aviato,
		aws,
		bandcamp,
		behance,
		behance_square,
		bimobject,
		bitbucket,
		bitcoin,
		bity,
		blackberry,
		black_tie,
		blogger,
		blogger_b,
		bluetooth,
		bluetooth_b,
		btc,
		buromobelexperte,
		buysellads,
		canadian_maple_leaf,
		cc_amazon_pay,
		cc_amex,
		cc_apple_pay,
		cc_diners_club,
		cc_discover,
		cc_jcb,
		cc_mastercard,
		cc_paypal,
		cc_stripe,
		cc_visa,
		centercode,
		centos,
		chrome,
		cloudscale,
		cloudsmith,
		cloudversify,
		codepen,
		codiepie,
		confluence,
		connectdevelop,
		contao,
		cpanel,
		creative_commons,
		creative_commons_by,
		creative_commons_nc,
		creative_commons_nc_eu,
		creative_commons_nc_jp,
		creative_commons_nd,
		creative_commons_pd,
		creative_commons_pd_alt,
		creative_commons_remix,
		creative_commons_sa,
		creative_commons_sampling,
		creative_commons_sampling_plus,
		creative_commons_share,
		creative_commons_zero,
		critical_role,
		css3,
		css3_alt,
		cuttlefish,
		d_and_d,
		d_and_d_beyond,
		dashcube,
		delicious,
		deploydog,
		deskpro,
		dev,
		deviantart,
		dhl,
		diaspora,
		digg,
		digital_ocean,
		discord,
		discourse,
		dochub,
		docker,
		draft2digital,
		dribbble,
		dribbble_square,
		dropbox,
		drupal,
		dyalog,
		earlybirds,
		ebay,
		edge,
		elementor,
		ello,
		ember,
		empire,
		envira,
		erlang,
		ethereum,
		etsy,
		expeditedssl,
		facebook,
		facebook_f,
		facebook_messenger,
		facebook_square,
		fantasy_flight_games,
		fedex,
		fedora,
		figma,
		firefox,
		firstdraft,
		first_order,
		first_order_alt,
		flickr,
		flipboard,
		fly,
		font_awesome,
		font_awesome_alt,
		font_awesome_flag,
		fonticons,
		fonticons_fi,
		fort_awesome,
		fort_awesome_alt,
		forumbee,
		foursquare,
		freebsd,
		free_code_camp,
		fulcrum,
		galactic_republic,
		galactic_senate,
		get_pocket,
		gg,
		gg_circle,
		git,
		github,
		github_alt,
		github_square,
		gitkraken,
		gitlab,
		git_square,
		gitter,
		glide,
		glide_g,
		gofore,
		goodreads,
		goodreads_g,
		google,
		google_drive,
		google_play,
		google_plus,
		google_plus_g,
		google_plus_square,
		google_wallet,
		gratipay,
		grav,
		gripfire,
		grunt,
		gulp,
		hacker_news,
		hacker_news_square,
		hackerrank,
		hips,
		hire_a_helper,
		hooli,
		hornbill,
		hotjar,
		houzz,
		html5,
		hubspot,
		imdb,
		instagram,
		intercom,
		internet_explorer,
		invision,
		ioxhost,
		itunes,
		itunes_note,
		java,
		jedi_order,
		jenkins,
		jira,
		joget,
		joomla,
		js,
		jsfiddle,
		js_square,
		kaggle,
		keybase,
		keycdn,
		kickstarter,
		kickstarter_k,
		korvue,
		laravel,
		lastfm,
		lastfm_square,
		leanpub,
		less,
		line,
		linkedin,
		linkedin_in,
		linode,
		linux,
		lyft,
		magento,
		mailchimp,
		mandalorian,
		markdown,
		mastodon,
		maxcdn,
		medapps,
		medium,
		medium_m,
		medrt,
		meetup,
		megaport,
		mendeley,
		microsoft,
		mix,
		mixcloud,
		mizuni,
		modx,
		monero,
		napster,
		neos,
		nimblr,
		nintendo_switch,
		node,
		node_js,
		npm,
		ns8,
		nutritionix,
		odnoklassniki,
		odnoklassniki_square,
		old_republic,
		opencart,
		openid,
		opera,
		optin_monster,
		osi,
		page4,
		pagelines,
		palfed,
		patreon,
		paypal,
		penny_arcade,
		periscope,
		phabricator,
		phoenix_framework,
		phoenix_squadron,
		php,
		pied_piper,
		pied_piper_alt,
		pied_piper_hat,
		pied_piper_pp,
		pinterest,
		pinterest_p,
		pinterest_square,
		playstation,
		product_hunt,
		pushed,
		python,
		qq,
		quinscape,
		quora,
		raspberry_pi,
		ravelry,
		react,
		reacteurope,
		readme,
		rebel,
		reddit,
		reddit_alien,
		reddit_square,
		redhat,
		red_river,
		renren,
		replyd,
		researchgate,
		resolving,
		rev,
		rocketchat,
		rockrms,
		r_project,
		safari,
		sass,
		schlix,
		scribd,
		searchengin,
		sellcast,
		sellsy,
		servicestack,
		shirtsinbulk,
		shopware,
		simplybuilt,
		sistrix,
		sith,
		sketch,
		skyatlas,
		skype,
		slack,
		slack_hash,
		slideshare,
		snapchat,
		snapchat_ghost,
		snapchat_square,
		soundcloud,
		sourcetree,
		speakap,
		spotify,
		squarespace,
		stack_exchange,
		stack_overflow,
		staylinked,
		steam,
		steam_square,
		steam_symbol,
		sticker_mule,
		strava,
		stripe,
		stripe_s,
		studiovinari,
		stumbleupon,
		stumbleupon_circle,
		superpowers,
		supple,
		suse,
		teamspeak,
		telegram,
		telegram_plane,
		tencent_weibo,
		themeco,
		themeisle,
		the_red_yeti,
		think_peaks,
		trade_federation,
		trello,
		tripadvisor,
		tumblr,
		tumblr_square,
		twitch,
		twitter,
		twitter_square,
		typo3,
		uber,
		ubuntu,
		uikit,
		uniregistry,
		untappd,
		ups,
		usb,
		usps,
		ussunnah,
		vaadin,
		viacoin,
		viadeo,
		viadeo_square,
		viber,
		vimeo,
		vimeo_square,
		vimeo_v,
		vine,
		vk,
		vnv,
		vuejs,
		weebly,
		weibo,
		weixin,
		whatsapp,
		whatsapp_square,
		whmcs,
		wikipedia_w,
		windows,
		wix,
		wizards_of_the_coast,
		wolf_pack_battalion,
		wordpress,
		wordpress_simple,
		wpbeginner,
		wpexplorer,
		wpforms,
		wpressr,
		xbox,
		xing,
		xing_square,
		yahoo,
		yandex,
		yandex_international,
		yarn,
		y_combinator,
		yelp,
		yoast,
		youtube,
		youtube_square,
		zhihu,

		// Backwards compat with 4.7
		address_book_o = 10000 + address_book,
		address_card_o = 10000 + address_card,
		area_chart = 10000 + chart_area,
		arrow_circle_o_down = 10000 + arrow_alt_circle_down,
		arrow_circle_o_left = 10000 + arrow_alt_circle_left,
		arrow_circle_o_right = 10000 + arrow_alt_circle_right,
		arrow_circle_o_up = 10000 + arrow_alt_circle_up,
		arrows = 10000 + arrows_alt,
		arrows_h = 10000 + arrows_alt_h,
		arrows_v = 10000 + arrows_alt_v,
		asl_interpreting = 10000 + american_sign_language_interpreting,
		automobile = 10000 + car,
		bank = 10000 + piggy_bank,
		bar_chart = 10000 + chart_bar,
		bar_chart_o = 10000 + chart_bar,
		bathtub = 10000 + bath,
		battery = 10000 + battery_full,
		battery_0 = 10000 + battery_empty,
		battery_1 = 10000 + battery_quarter,
		battery_2 = 10000 + battery_half,
		battery_3 = 10000 + battery_three_quarters,
		battery_4 = 10000 + battery_full,
		bell_o = 10000 + bell,
		bell_slash_o = 10000 + bell_slash,
		bitbucket_square = 10000 + bitbucket,
		bookmark_o = 10000 + bookmark,
		building_o = 10000 + building,
		cab = 10000 + taxi,
		calendar_check_o = 10000 + calendar_check,
		calendar_minus_o = 10000 + calendar_minus,
		calendar_o = 10000 + calendar,
		calendar_plus_o = 10000 + calendar_plus,
		calendar_times_o = 10000 + calendar_times,
		
		caret_square_o_down = 10000 + caret_down,
		caret_square_o_left = 10000 + caret_left,
		caret_square_o_right = 10000 + caret_right,
		caret_square_o_up = 10000 + caret_up,
		cc = 10000 + credit_card,
		chain = 10000 + link,
		chain_broken = 10000 + unlink,
		check_circle_o = 10000 + check_circle,
		check_square_o = 10000 + check_square,
		circle_o = 10000 + circle,
		circle_o_notch = 10000 + circle,
		circle_thin = 10000 + circle,
		clock_o = 10000 + clock,
		close = 10000 + window_close,
		cloud_download = 10000 + cloud_download_alt,
		cloud_upload = 10000 + cloud_upload_alt,
		cny = 10000 + yen_sign,
		code_fork = 10000 + code_branch,
		comment_o = 10000 + comment,
		commenting = 10000 + comment_dots,
		commenting_o = 10000 + comment_dots,
		comments_o = 10000 + comments,
		credit_card_alt = 10000 + credit_card,
		cutlery = 10000 + utensils,
		dashboard = 10000 + tachometer_alt,
		deafness = 10000 + deaf,
		dedent = 10000 + outdent,
		diamond = 10000 + gem,
		dollar = 10000 + dollar_sign,
		dot_circle_o = 10000 + dot_circle,
		drivers_license = 10000 + id_badge,
		drivers_license_o = 10000 + id_badge,
		eercast = 10000 + sellcast,
		envelope_o = 10000 + envelope,
		envelope_open_o = 10000 + envelope_open,
		eur = 10000 + euro_sign,
		euro = 10000 + euro_sign,
		exchange = 10000 + exchange_alt,
		external_link = 10000 + external_link_alt,
		external_link_square = 10000 + external_link_alt,
		eyedropper = 10000 + eye_dropper,
		fa = 10000 + font_awesome,
		facebook_official = 10000 +  facebook,
		feed = 10000 + rss,
		file_archive_o = 10000 + file_archive,
		file_audio_o = 10000 + file_audio,
		file_code_o = 10000 + file_code,
		file_excel_o = 10000 + file_excel,
		file_image_o = 10000 + file_image,
		file_movie_o = 10000 + file_video,
		file_o = 10000 + file,
		file_pdf_o = 10000 + file_pdf,
		file_photo_o = 10000 + file_image,
		file_picture_o = 10000 + file_image,
		file_powerpoint_o = 10000 + file_powerpoint,
		file_sound_o = 10000 + file_audio,
		file_text = 10000 + file_alt,
		file_text_o = 10000 + file_alt,
		file_video_o = 10000 + file_video,
		file_word_o = 10000 + file_word,
		file_zip_o = 10000 + file_archive,
		files_o = 10000 + copy,
		flag_o = 10000 + flag,
		flash = 10000 + bolt,
		floppy_o = 10000 + save,
		folder_o = 10000 + folder,
		folder_open_o = 10000 + folder_open,
		frown_o = 10000 + frown,
		futbol_o = 10000 + futbol,
		gbp =10000 +  pound_sign,
		ge = 10000 + empire,
		gear = 10000 + cog,
		gears = 10000 + cogs,
		gittip = 10000 + gratipay,
		glass = 10000 + wine_glass,
		google_plus_circle = 10000 + google_plus,
		google_plus_official = 10000 + google_plus,
		group = 10000 + users,
		hand_grab_o = 10000 + hand_rock,
		hand_lizard_o = 10000 + hand_lizard,
		hand_o_down = 10000 + hand_point_down,
		hand_o_left = 10000 + hand_point_left,
		hand_o_right = 10000 + hand_point_right,
		hand_o_up = 10000 + hand_point_up,
		hand_paper_o = 10000 + hand_paper,
		hand_peace_o = 10000 + hand_peace,
		hand_pointer_o = 10000 + hand_pointer,
		hand_rock_o = 10000 + hand_rock,
		hand_scissors_o = 10000 + hand_scissors,
		hand_spock_o = 10000 + hand_spock,
		hand_stop_o = 10000 + hand_paper,
		handshake_o = 10000 + handshake,
		hard_of_hearing = 10000 + deaf,
		hdd_o = 10000 + hdd,
		header = 10000 + heading,
		heart_o = 10000 + heart,
		hospital_o = 10000 + hospital,
		hourglass_1 = 10000 + hourglass_end,
		hourglass_2 = 10000 + hourglass_half,
		hourglass_3 = 10000 + hourglass_start,
		hourglass_o = 10000 + hourglass,
		id_card_o = 10000 + id_card,
		ils = 10000 + shekel_sign,
		inr = 10000 + rupee_sign,
		institution = 10000 + university,
		intersex = 10000 + transgender,
		jpy = 10000 + yen_sign,
		keyboard_o = 10000 + keyboard,
		krw = 10000 + won_sign,
		legal = 10000 + gavel,
		lemon_o = 10000 + lemon,
		level_down = 10000 + level_down_alt,
		level_up = 10000 + level_up_alt,
		life_bouy = 10000 + life_ring,
		life_buoy = 10000 + life_ring,
		life_saver = 10000 + life_ring,
		lightbulb_o = 10000 + lightbulb,
		line_chart = 10000 + chart_line,
		linkedin_square = 10000 + linkedin,
		long_arrow_down = 10000 + long_arrow_alt_down,
		long_arrow_left = 10000 + long_arrow_alt_left,
		long_arrow_right = 10000 + long_arrow_alt_right,
		long_arrow_up = 10000 + long_arrow_alt_up,
		mail_forward = 10000 + share,
		mail_reply = 10000 + reply,
		mail_reply_all = 10000 + reply_all,
		map_o = 10000 + map,
		meh_o = 10000 + meh,
		minus_square_o = 10000 + minus_square,
		mobile_phone = 10000 + phone,
		money = 10000 + money_bill_alt,
		moon_o = 10000 + moon,
		mortar_board = 10000 + graduation_cap,
		navicon = 10000 + bars,
		newspaper_o = 10000 + newspaper,
		paper_plane_o = 10000 + paper_plane,
		pause_circle_o = 10000 + pause_circle,
		pencil = 10000 + pencil_alt,
		pencil_square = 10000 + pencil_alt,
		pencil_square_o = 10000 + pencil_alt,
		photo = 10000 + image,
		picture_o = 10000 + image,
		pie_chart = 10000 + chart_pie,
		play_circle_o = 10000 + play_circle,
		plus_square_o = 10000 + play,
		question_circle_o = 10000 + question,
		ra = 10000 + rebel,
		refresh = 10000 + sync,
		remove = 10000 + times,
		reorder = 10000 + bars,
		repeat = 10000 + redo,
		resistance = 10000 + rebel,
		rmb = 10000 + yen_sign,
		rotate_left = 10000 + undo,
		rotate_right = 10000 + redo,
		rouble = 10000 + ruble_sign,
		rub = 10000 + ruble_sign,
		ruble = 10000 + ruble_sign,
		rupee = 10000 + rupee_sign,
		s15 = 10000 + bath,
		scissors = 10000 + cut,
		send = 10000 + paper_plane,
		send_o = 10000 + paper_plane,
		share_square_o = 10000 + share_square,
		shekel = 10000 + shekel_sign,
		sheqel = 10000 + shekel_sign,
		shield = 10000 + shield_alt,
		sign_in = 10000 + sign_in_alt,
		sign_out = 10000 + sign_out_alt,
		signing = 10000 + american_sign_language_interpreting,
		sliders = 10000 + sliders_h,
		smile_o = 10000 + smile,
		snowflake_o = 10000 + snowflake,
		soccer_ball_o = 10000 + futbol,
		sort_alpha_asc = 10000 + sort_alpha_down,
		sort_alpha_desc = 10000 + sort_alpha_up,
		sort_amount_asc = 10000 + sort_amount_down,
		sort_amount_desc = 10000 + sort_amount_up,
		sort_asc = 10000 + sort_down,
		sort_desc = 10000 + sort_up,
		sort_numeric_asc = 10000 + sort_numeric_down,
		sort_numeric_desc = 10000 + sort_numeric_up,
		spoon = 10000 + utensil_spoon,
		square_o = 10000 + square,
		star_half_empty = 10000 + star,
		star_half_full = 10000 + star_half_alt,
		star_half_o = 10000 + star_half_alt,
		star_o = 10000 + star,
		sticky_note_o = 10000 + sticky_note,
		stop_circle_o = 10000 + stop_circle,
		sun_o = 10000 + sun,
		support = 10000 + life_ring,
		tachometer = 10000 + tachometer_alt,
		television = 10000 + tv,
		thermometer_0 = 10000 + thermometer_empty,
		thermometer_1 = 10000 + thermometer_quarter,
		thermometer_2 = 10000 + thermometer_half,
		thermometer_3 = 10000 + thermometer_three_quarters,
		thermometer_4 = 10000 + thermometer_full,
		thumb_tack = 10000 + thumbs_down,
		thumbs_o_down = 10000 + thumbs_down,
		thumbs_o_up = 10000 + thumbs_up,
		ticket = 10000 + ticket_alt,
		times_circle_o = 10000 + times_circle,
		times_rectangle = 10000 + times,
		times_rectangle_o = 10000 + times,
		toggle_down = 10000 + caret_square_down,
		toggle_left = 10000 + caret_square_left,
		toggle_right = 10000 + caret_square_right,
		toggle_up = 10000 + caret_up,
		trash_o = 10000 + trash,
		_try = 10000 + lira_sign,
		turkish_lira = 10000 + lira_sign,
		unsorted = 10000 + sort,
		usd = 10000 + dollar_sign,
		user_circle_o = 10000 + user_circle,
		user_o = 10000 + user,
		vcard = 10000 + address_card,
		vcard_o = 10000 + address_card,
		volume_control_phone = 10000 + phone_volume,
		warning = 10000 + exclamation_triangle,
		wheelchair_alt = 10000 + wheelchair,
		window_close_o = 10000 + window_close,
		won = 10000 + won_sign,
		y_combinator_square = 10000 + y_combinator,
		yc = 10000 + y_combinator,
		yc_square = 10000 + y_combinator,
		yen = 10000 + yen_sign,
		youtube_play = 10000 + youtube
	}

	public static class FontAwesomeIconsExtensions
	{
		public static string GetIconName(this FontAwesomeIcons icon)
		{
			var intIcon = (int)icon;
			if (intIcon > 10000) {
				icon = (FontAwesomeIcons)(intIcon - 10000);
			}

			return Enum.GetName(typeof(FontAwesomeIcons), icon).TrimStart('_').Replace("_", "-");
		}
	}


}
